# Generated by Django 5.1.5 on 2026-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_text', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('nutrition', 'Nutrition'), ('fitness', 'Fitness'), ('wellness', 'Wellness'), ('mental_health', 'Mental Health')], max_length=15)),
                ('date_published', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='FitnessRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15)),
                ('target_area', models.CharField(choices=[('full_body', 'Full Body'), ('core', 'Core & Abs'), ('upper_body', 'Upper Body'), ('lower_body', 'Lower Body'), ('flexibility', 'Flexibility'), ('cardio', 'Cardio'), ('yoga', 'Yoga'), ('pelvic', 'Pelvic Floor')], max_length=15)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('description', models.TextField()),
                ('exercises', models.TextField(help_text='Exercise details with sets/reps')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fitness/')),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NutritionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('diet', 'Diet & Nutrition'), ('recipes', 'Healthy Recipes'), ('supplements', 'Supplements'), ('hydration', 'Hydration'), ('weight', 'Weight Management'), ('hormonal', 'Hormonal Health Diet'), ('pregnancy', 'Pregnancy Nutrition'), ('pcos', 'PCOS Diet')], max_length=20)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='nutrition/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
