# Generated by Django 5.1.5 on 2026-06-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='ai_abnormal_findings',
            field=models.TextField(blank=True, help_text='Highlighted abnormal findings and key values', null=True),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated simple explanation of the report', null=True),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='summary_language',
            field=models.CharField(choices=[('en', 'English'), ('te', 'Telugu (తెలుగు)'), ('hi', 'Hindi (हिन्दी)'), ('ta', 'Tamil (தமிழ்)')], default='en', help_text='Language for the AI-generated summary', max_length=10),
        ),
    ]
