# Generated by Django 5.1.5 on 2026-05-22 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('mindfulness', 'Mindfulness'), ('stress', 'Stress Management'), ('anxiety', 'Anxiety'), ('depression', 'Depression'), ('self_care', 'Self Care'), ('relationships', 'Relationships'), ('sleep', 'Sleep Health'), ('breathing', 'Breathing Exercises')], max_length=20)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('exercise', 'Exercise'), ('video', 'Video'), ('guide', 'Guide')], default='article', max_length=10)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mental_health/')),
                ('external_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood_score', models.IntegerField(choices=[(1, '😞 Very Low'), (2, '😔 Low'), (3, '😐 Okay'), (4, '🙂 Good'), (5, '😊 Great'), (6, '🤗 Excellent'), (7, '😄 Amazing')])),
                ('activities', models.CharField(blank=True, help_text='Comma-separated activities', max_length=500)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('stress_level', models.IntegerField(default=5, help_text='1-10 scale')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
