# Generated by Django 5.1.5 on 2026-05-22 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('blood_test', 'Blood Test / Lab Report'), ('prescription', 'Prescription'), ('scan', 'Ultrasound / X-Ray / Scan'), ('vaccine', 'Vaccination Record'), ('discharge', 'Discharge Summary'), ('other', 'Other Document')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='health_reports/%Y/%m/%d/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('report_date', models.DateField(help_text='Date on the report/document')),
                ('doctor_name', models.CharField(blank=True, help_text='Prescribing or consulting doctor', max_length=150)),
                ('hospital_clinic', models.CharField(blank=True, help_text='Hospital or diagnostic clinic', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Brief notes or diagnosis summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Report',
                'verbose_name_plural': 'Health Reports',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
