# Generated by Django 5.1.5 on 2026-05-22 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cycle_length', models.IntegerField(blank=True, help_text='Days between this and next period', null=True)),
                ('period_length', models.IntegerField(blank=True, help_text='Duration of period in days', null=True)),
                ('flow_intensity', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='medium', max_length=10)),
                ('symptoms', models.CharField(blank=True, help_text='Comma-separated symptoms', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cycle Log',
                'verbose_name_plural': 'Cycle Logs',
                'ordering': ['-start_date'],
            },
        ),
    ]
